### PR TITLE
Added Dockerfile implementation for luacheck repository

### PR DESCRIPTION
**Pull request by MartinBroers**
A simple Dockerfile pulls in the repository and builds the repo inside the container. The container hence will always contain the latest version of the master branch. The container can be used to check any lua source folder without installing any of the dependencies on the host operating system, making it an ideal tool for CI integration.
To build it:
`docker build -t luacheck .`
To run it:
`docker run -it --rm -v /home/martin/src/luacheck:/workdir luacheck`

### CODE REVIEW

**Comment by mujz** [comment]
@MartinBroers are you planning on merging this in? It would be great if this image gets pushed to docker hub to make it easy to run `luacheck` in a CI environment without having to install lua and luarocks in order to run the linter.

**Comment by linuxmaniac** [comment]
@mujz sadly no one will merge this, take a look over #198

**Comment by MartinBroers** [comment]
@mujz I will push the dockerimage somewhere today as soon as I'll get time to do it! It won't be merged as @linuxmaniac pointed, but I can still push it to dockerhub, no problem!

**Comment by MartinBroers** [comment]
Hi @mujz I have uploaded the dockerimage to Dockerhub, you can pull it:
`docker pull martinbrothers/luacheck:latest`

**Comment by alerque** [comment]
@MartinBroers If you are still around would you mind opening this branch as a PR against [this repository](https://github.com/lunarmodules/luacheck) (the new canonical home, see #198). I would like to set something like this up. I will change a number of the implementation details, but it would be nice to build on and include your work instead of just passing it over. My goal would be to also include a container published to GHCR that can be used easily *as* a GitHub Action to lint other projects. That requires a working Docker build.

**Comment by MartinBroers** [comment]
@alerque I have created the MR. If you need my assistance, please let me know. Curious to see what changes you have in your mind.

**Comment by alerque** [comment]
Thanks! I'll get on it (there might be a delay as I'm leaving for extended travels soon, but it' son my list). You can probably close this PR by the way. Nobody has access to managing issues/PRs here any more so only closing your own will signal what things are migrated.

**Pull request closed without merging**
